import { preprocessMarkdown } from './math';

interface PDFOptions {
  title?: string;
  author?: string;
  includeCover?: boolean;
  includeToc?: boolean;
}

function escapeHtml(text: string): string {
  const map: { [key: string]: string } = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}

function extractHeadings(markdown: string): { level: number; text: string }[] {
  const headings: { level: number; text: string }[] = [];
  const lines = markdown.split('\n');

  lines.forEach((line) => {
    const match = line.match(/^(#{1,6})\s+(.*)$/);
    if (match) {
      headings.push({
        level: match[1].length,
        text: match[2],
      });
    }
  });

  return headings;
}

function markdownToHtml(markdown: string): string {
  let html = preprocessMarkdown(markdown);

  // Headers
  html = html.replace(/^### (.*?)$/gm, '<h3>$1</h3>');
  html = html.replace(/^## (.*?)$/gm, '<h2>$1</h2>');
  html = html.replace(/^# (.*?)$/gm, '<h1>$1</h1>');

  // Code blocks
  html = html.replace(/```([\s\S]*?)```/g, '<pre><code>$1</code></pre>');

  // Inline code
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>');

  // Bold
  html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/__(.+?)__/g, '<strong>$1</strong>');

  // Italic
  html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');
  html = html.replace(/_(.+?)_/g, '<em>$1</em>');

  // Links
  html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');

  // Line breaks
  html = html.replace(/\n\n/g, '</p><p>');
  html = `<p>${html}</p>`;

  return html;
}

export async function generatePDFHTML(
  markdown: string,
  options: PDFOptions = {}
): Promise<string> {
  const {
    title = 'Document',
    author = 'Generated by Markdown to Beautiful PDF Studio',
    includeCover = true,
    includeToc = true,
  } = options;

  const headings = extractHeadings(markdown);
  const contentHtml = markdownToHtml(markdown);

  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <link href="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css" rel="stylesheet">
  <style>
    * { margin: 0; padding: 0; }
    body { font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', sans-serif; line-height: 1.6; color: #1a1a1a; }
    .page { page-break-after: always; padding: 40mm; }
    .page:last-child { page-break-after: avoid; }
    h1 { font-size: 48px; font-weight: 700; margin: 40px 0 20px 0; color: #000; }
    h2 { font-size: 28px; font-weight: 600; margin: 30px 0 15px 0; color: #222; }
    h3 { font-size: 24px; font-weight: 500; margin: 20px 0 10px 0; color: #333; }
    p { font-size: 16px; margin: 16px 0; }
    code { background: #f5f5f5; padding: 2px 6px; border-radius: 3px; font-family: 'Monaco', 'Courier New', monospace; font-size: 14px; }
    pre { background: #f8f8f8; padding: 16px; border-radius: 6px; overflow-x: auto; margin: 16px 0; }
    pre code { background: transparent; padding: 0; }
    a { color: #0066cc; text-decoration: underline; }
    strong { font-weight: 600; }
    em { font-style: italic; }
    blockquote { border-left: 4px solid #ddd; padding-left: 16px; margin: 16px 0; color: #666; font-style: italic; }
    .cover { display: flex; flex-direction: column; justify-content: center; align-items: center; height: 100%; text-align: center; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; }
    .cover h1 { color: white; font-size: 56px; margin: 0 0 20px 0; }
    .cover .author { color: rgba(255, 255, 255, 0.9); font-size: 18px; margin: 0; }
    .toc { padding: 40mm; }
    .toc h2 { margin-top: 0; }
    .toc-entry { margin: 8px 0; padding-left: 20px; }
    .toc-entry.level-2 { padding-left: 40px; }
    .toc-entry.level-3 { padding-left: 60px; }
    .toc-entry a { color: #0066cc; text-decoration: none; }
    .toc-entry a:hover { text-decoration: underline; }
    .content { }
  </style>
</head>
<body>`;

  if (includeCover) {
    html += `
    <div class="page cover">
      <h1>${escapeHtml(title)}</h1>
      <p class="author">${escapeHtml(author)}</p>
    </div>`;
  }

  if (includeToc && headings.length > 0) {
    html += '<div class="page toc"><h2>Table of Contents</h2>';
    headings.forEach((heading) => {
      html += `<div class="toc-entry level-${heading.level}"><a href="#heading-${heading.text.replace(/\s+/g, '-').toLowerCase()}">${escapeHtml(heading.text)}</a></div>`;
    });
    html += '</div>';
  }

  html += `<div class="page content">${contentHtml}</div>`;
  html += '</body></html>';

  return html;
}
